#------------------------------
# Github Actions test1
#
#------------------------------
name: GitHub-Actions-test1
env:
   APPLICATION_NAME    : "MyFlask"
   DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in testing
      run : echo "Hello World from Testing job"
   
    - name: Execure few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Appication name: ${{ env.APPLICATION_NAME }}"
    - name: List current folder
      run: ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run: ls -la
      
    
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is Job level Variable1"
      VAR2: "This is Job level Variable2"
    
    steps:
    - name: Print Hello Message in deploy
      run: echo "Hello World from Deploy"
      
    - name: Print env vars
      run: 
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is Supper local Environment variable"
        
    - name: Printing Deployment package
      run : echo "Deplyo pakcage name is ${{ env.DEPLOY_PACKAGE_NAME }}"

    - name: Lets test some packages of they are here
      run: aws --version
      
    - name: Lets test some packages of the are here
      run: zip --version
